### ISSUE TITLE
trouble with saturated mutagenesis

### ISSUE THREAD

**Issue by rschwess** [davek44/Basset#23] opened 2016-06-20 12:13 UTC
Hi there,

Sorry, feels like I'm ploughing through the functions and hitting everything that can go wrong ;]

Trying to use the saturated mutatgenesis I faced problems and tried to fall back on the tutorial chr7 hox ctcf site example location:

`~/toolsBasset/$ basset_sat.py -t 3 -n 200 -o satmut_hox cnn_full_with_prim_erythroid/dnase_with_prim_erythroid_cnn_best.decuda.th ./hox_test_seq.fa 
basset_sat_predict.lua  -center_nt 200 cnn_full_with_prim_erythroid/dnase_with_prim_erythroid_cnn_best.decuda.th satmut_hox/model_in.h5 satmut_hox/model_out.h5`

Predicting sequence 1 variants  
Traceback (most recent call last):
  File "/home/ron/tools/Basset/src/basset_sat.py", line 367, in <module>
    main()
  File "/home/ron/tools/Basset/src/basset_sat.py", line 206, in main
    g = sns.heatmap(preds_heat, vmin=0, vmax=1, linewidths=0, xticklabels=target_labels, yticklabels=False, cbar_kws={"orientation": "horizontal"})
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 452, in heatmap
    mask)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 140, in __init__
    self.xticklabels = xticklabels[xstart:xend:xstep]
TypeError: 'NoneType' object has no attribute '__getitem__'

`~/toolsBasset/\$ ll satmut_hox/`
total 1092
drwxrwxr-x  2 ron ron    4096 Jun 20 12:59 ./
drwxrwxr-x 11 ron ron   12288 Jun 20 13:04 ../
-rw-rw-r--  1 ron ron    6944 Jun 20 13:06 model_in.h5
-rw-rw-r--  1 ron ron 1058144 Jun 20 13:06 model_out.h5
-rw-rw-r--  1 ron ron       0 Jun 20 13:06 preds.txt
-rw-rw-r--  1 ron ron       0 Jun 20 13:06 table.txt

I was trying to run with my own trained model (your 164 selected tissues + on test set of our own). Trying the same with your provided pre-trained model results in exactly the same error output independent of the selected cell type to predict. 

Also noteworthy: the randomly selecting and mutating sequences from the already extracted sequences (as described in the sat_mut tutorial) seems to work fine) 

Cheers,
Ron

**Comment by davek44** [comment] 2016-06-22 21:20
No, keep bringing the feedback! This one's caused by bad x-axis labels of the targets. If you want labels, pass them with "--targets_file". Otherwise, I think I fixed it to not crash when it doesn't have them.

**Comment by vagarwal87** [comment] 2016-09-09 00:57
I'm not quite sure what I'm doing wrong, but I'm running into a similar issue (my code is from Aug 23).

This is the command I run and the corresponding output:

./basset_sat.py --cuda -t 1 --targets_file testout -s 10 -n 100 mythfile.th myh5file.h5
basset_sat_predict.lua -cuda -center_nt 100 mythfile.th heat/model_in.h5 heat/model_out.h5

Predicting sequence 1 variants
Predicting sequence 2 variants
Predicting sequence 3 variants
Predicting sequence 4 variants
Predicting sequence 5 variants
Predicting sequence 6 variants
Predicting sequence 7 variants
Predicting sequence 8 variants
Predicting sequence 9 variants
Predicting sequence 10 variants

/home/ubuntu/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py:134: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if xticklabels == []:
Traceback (most recent call last):
  File "./basset_sat.py", line 373, in <module>
    main()
  File "./basset_sat.py", line 216, in main
    seq_mod_preds_cell = seq_mod_preds[si,:,:,ci]
IndexError: index 1 is out of bounds for axis 3 with size 1

Any idea how to fix this error (maybe it's related to the other one mentioned)?

**Comment by davek44** [comment] 2016-09-17 22:44
How many targets did you train on? It looks like there's just one target, but you're asking it to consider a second target (-t is 0-based indexing so -t 1 means consider the second target).

**Comment by vagarwal87** [comment] 2016-09-19 23:59
Oh I see -- correct me if I'm wrong, but it sounds like a "target" alludes to a column of the output matrix one is trying to predict, in which case yes, I had a single target, and the issue was fixed by the -t 0 option. Thanks for the recommendation, I think I was a bit confused by the terminology of what the "target index" precisely alluded to.

**Comment by davek44** [comment] 2016-09-20 07:52
That's right, you've got it

**Closed by davek44** 2016-09-20 07:52 UTC
